"""Create messages_notifications table

Revision ID: 1fdeb3952dde
Revises: 7e4c0d07bf0b
Create Date: 2024-11-19 18:37:52.898419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fdeb3952dde'
down_revision: Union[str, None] = '7e4c0d07bf0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
