"""Update messages table structure

Revision ID: 77c8c02db36d
Revises: b98e9634dd3a
Create Date: 2024-11-20 10:38:08.973975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c8c02db36d'
down_revision: Union[str, None] = 'b98e9634dd3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_sender_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('message_reciver_id', sa.Integer(), nullable=False))
    op.drop_constraint('messages_message_sender_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_message_reciver_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['message_sender_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['message_reciver_id'], ['id'])
    op.drop_column('messages', 'message_reciver')
    op.drop_column('messages', 'message_sender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_sender', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('message_reciver', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_message_reciver_fkey', 'messages', 'users', ['message_reciver'], ['id'])
    op.create_foreign_key('messages_message_sender_fkey', 'messages', 'users', ['message_sender'], ['id'])
    op.drop_column('messages', 'message_reciver_id')
    op.drop_column('messages', 'message_sender_id')
    # ### end Alembic commands ###
