"""add token to users and drop users_session_data

Revision ID: c40dc9b38a70
Revises: ffa086b170d0
Create Date: 2024-11-18 15:27:59.427366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40dc9b38a70'
down_revision: Union[str, None] = 'ffa086b170d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_session_data_id', table_name='users_session_data')
    op.drop_table('users_session_data')
    op.add_column('users', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    op.create_table('users_session_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_session_data_pkey')
    )
    op.create_index('ix_users_session_data_id', 'users_session_data', ['id'], unique=False)
    # ### end Alembic commands ###
