"""Add tasks table

Revision ID: cd7098b42e82
Revises: 41eac2844d76
Create Date: 2024-12-19 18:08:49.922165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7098b42e82'
down_revision: Union[str, None] = '41eac2844d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('task_content', sa.String(), nullable=False),
    sa.Column('task_executor', sa.Integer(), nullable=True),
    sa.Column('task_director', sa.Integer(), nullable=True),
    sa.Column('task_progress', sa.String(length=50), nullable=False),
    sa.Column('task_date', sa.DateTime(), nullable=False),
    sa.Column('task_deadline', sa.DateTime(), nullable=True),
    sa.Column('task_status', sa.String(length=50), nullable=False),
    sa.Column('task_priority', sa.String(length=50), nullable=True),
    sa.Column('task_executor_role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_director'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_executor'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
