"""Add refresh_token to users

Revision ID: e32826910022
Revises: 337d682f2ee8
Create Date: 2024-11-22 20:30:32.690386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e32826910022'
down_revision: Union[str, None] = '337d682f2ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True))
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###
