"""Remove access_token from users

Revision ID: f302f9e9af7d
Revises: e32826910022
Create Date: 2024-11-22 22:56:46.059789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f302f9e9af7d'
down_revision: Union[str, None] = 'e32826910022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'messages', 'users', ['message_sender_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['message_receiver_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['notification_receiver_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['notification_sender_id'], ['id'])
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    # ### end Alembic commands ###
