"""Rename message_reciver_id to message_receiver_id

Revision ID: fe15ebc6a054
Revises: 4ddcbeebd74b
Create Date: 2024-11-20 13:01:50.188399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe15ebc6a054'
down_revision: Union[str, None] = '4ddcbeebd74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
